services:
  - type: web
    name: tgscraper-userbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
